apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: goapp241108
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-artifactory.apps.rhopp241108.devcluster.openshift.com/rhtap-docker/goapp:jenkins-cba0b915d0adbb00e276c3f2bbda73b5da4cce29
          name: container-image
