apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goapp241108
  janus-idp.io/tekton: goapp241108
  backstage.io/kubernetes-id: goapp241108
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp241108
resources:
- deployment.yaml
- route.yaml
- service.yaml
