apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: goapp241108
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goapp241108 
  name: goapp241108
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: goapp241108
    weight: 100 
